---
kind: pipeline
type: docker
name: avr-toolchain-beta

platform:
  os: linux
  arch: amd64

steps:
  - name: version
    commands:
      - cat avr-toolchain/VERSION > .tags
  - name: build-beta
    image: plugins/docker
    settings:
      repo: embeddedreality/avr-toolchain
      dockerfile: avr-toolchain/Dockerfile
      username:
        from_secret: repo_username
      password:
        from_secret: repo_password
